services:
    mongo-express:
        image: mongo-express
        container_name: nextjs-pokeapi-exercise-mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_URL: "mongodb://root:root@mongo:27017"
        links:
            - mongo
    next:
        image: nextjs-pokeapi-exercise-dev
        container_name: nextjs-pokeapi-exercise-next
        build:
            context: .
            target: development
        volumes:
            - .:/app
    